### ISSUE TITLE
Inference error

### ISSUE THREAD

**Issue by didibaba** [rishizek/tensorflow-deeplab-v3#6]
When I ran inference.py with the model downloaded from drop box, I just came across the problems below. Anyone has the same situation?

> 
> INFO:tensorflow:Using default config.
> INFO:tensorflow:Using config: {'_model_dir': './model/from_git', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000002B40EDA7F60>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
> INFO:tensorflow:Calling model_fn.
> INFO:tensorflow:Done calling model_fn.
> INFO:tensorflow:Graph was finalized.
> 2018-03-16 00:25:00.759874: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> 2018-03-16 00:25:02.029733: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1212] Found device 0 with properties:
> name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.569
> pciBusID: 0000:02:00.0
> totalMemory: 6.00GiB freeMemory: 4.98GiB
> 2018-03-16 00:25:02.036896: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1312] Adding visible gpu devices: 0
> 2018-03-16 00:25:02.814725: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4750 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:02:00.0, compute capability: 6.1)
> INFO:tensorflow:Restoring parameters from ./model/from_git\model.ckpt-30452
> 2018-03-16 00:25:03.667033: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1202] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key assp/conv_1x1/BatchNorm/beta not found in checkpoint
> Traceback (most recent call last):
>   File "C:\Users\whzon\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1361, in _do_call
>     return fn(*args)
>   File "C:\Users\whzon\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _run_fn
>     target_list, status, run_metadata)
>   File "C:\Users\whzon\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: Key assp/conv_1x1/BatchNorm/beta not found in checkpoint
>          [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
>          [[Node: save/RestoreV2/_65 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_84_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by rishizek** [comment]
Hi @didibaba , 
the problem is described in the following line:
> Not found: Key assp/conv_1x1/BatchNorm/beta not found in checkpoint

Initially I was incorrectly named 'aspp' layer as 'assp', and later I corrected the name.
check [here](https://github.com/rishizek/tensorflow-deeplab-v3/commit/35c98ff170afd3f15fc23ecd75b0d63da7cdbe1f)
Please update the code to latest version, then the problem should be solved.
